### ISSUE TITLE
Other miscellaneous semantics questions...

### ISSUE THREAD

**Issue by rozele** [joescars/Functions.Bindings.DataLakeStore#10]
I'll comment here with other semantics questions.

1. Can you ever use an `IAsyncCollector<T>` after calling `FlushAsync`? If so, you may need to clear the `_items` collection in `DataLakeStoreOutputAsyncCollector`.
2. Do you need to use the `[AppSetting]` attribute for Functions v1? If not, it may be better to conditionally compile it out with `#if` rather than suppressing the `Obsolete` warning.
3. Is there something internal to the `Microsoft.Rest.ClientRuntime.Azure.Authentication` library that requires a `SynchronizationContext`? Otherwise, it seems you don't need https://github.com/joescars/Functions.Bindings.DataLakeStore/blob/29b1ba971cbaede276b9779fa4027fd25bb09f5e/Functions.Bindings.DataLakeStore/Services/DataLakeAdlsService.cs#L26 and I would also think you could achieve the same results for https://github.com/joescars/Functions.Bindings.DataLakeStore/blob/29b1ba971cbaede276b9779fa4027fd25bb09f5e/Functions.Bindings.DataLakeStore/Services/DataLakeAdlsService.cs#L35 by replacing `.GetAwaiter().GetResults()` with just `.Result`.

**Comment by joescars** [comment]
1. No. either way I ended up removing this and updating directly in the `AddAsync` method

2. yes, it is required. 

3. You are correct it is not needed. This was addressed in an earlier commit https://github.com/joescars/Functions.Bindings.DataLakeStore/commit/f0a5f064da24d9a619b59f03c95ca3d85cd321ec#diff-219ec6dbe32854d7366d38892a3085c2
