### ISSUE TITLE
Minimize the public surface

### ISSUE THREAD

**Issue by rozele** [joescars/Functions.Bindings.DataLakeStore#3]
Make sure you provide a bare minimum API, as you want to minimize the legacy APIs you'll have to support as time progresses. E.g., do you need to expose the following:
* `DataLakeAdlsService` class?
* `DataLakeConfiguration` class?
* `DataLakeStoreStreamBuilder` class?

**Comment by joescars** [comment]
Good point. I've updated the following classes

- `DataLakeAdlsService`
- `DataLakeStoreOutputAsyncCollector`
- `DataLakeStoreStreamBuilder`

`DataLakeConfiguration` must remain public
