### ISSUE TITLE
DataLakeStoreStreamBuilder missing constructor logic?

### ISSUE THREAD

**Issue by rozele** [joescars/Functions.Bindings.DataLakeStore#4]
The .ctor for the `DataLakeStoreStreamBuilder` takes a `DataLakeConfiguration` parameter but doesn't do anything with it.
https://github.com/joescars/Functions.Bindings.DataLakeStore/blob/master/Functions.Bindings.DataLakeStore/DataLakeStoreStreamBuilder.cs#L15-L18

**Comment by joescars** [comment]
Good catch. Removed.
