### ISSUE TITLE
Miscellaneous suggestions for code style changes

### ISSUE THREAD

**Issue by rozele** [joescars/Functions.Bindings.DataLakeStore#5]
I'll comment on this issue with some miscellaneous code style suggestions.

**Comment by rozele** [comment]
https://github.com/joescars/Functions.Bindings.DataLakeStore/blob/master/Functions.Bindings.DataLakeStore/DataLakeStoreStreamBuilder.cs#L23-L25

```csharp
        public async Task<Stream> ConvertAsync(DataLakeStoreAttribute input, CancellationToken cancellationToken)
        {
            // Create ADLS client object
            var adlsClient = _adlsClient ?? (_adlsClient = DataLakeAdlsService.CreateAdlsClient(input.TenantID, input.ClientSecret, input.ApplicationId, input.AccountFQDN));

            return await adlsClient.GetReadStreamAsync(input.FileName);
        }
```

1. Remove async/await. You don't have any continuations here, so you can actually just return the same `Task<Stream>` created by `adlsClient.GetReadStreamAsync`.
2. Any thoughts on adding a lock around `_adlsClient`? I assume the reason you use the pattern:
`var adlsClient = _adlsClient ?? (_adlsClient = /* … */);` is because there is the potential for concurrent calls to `ConvertAsync`. If there is no concurrency issue, then you can probably simplify a bit and just use the field reference, i.e., `_adlsClient = _adlsClient ?? /* … */` and `return _adlsClient.GetReadStreamAsync(/*…*/)`

**Comment by rozele** [comment]
Unused private field at: https://github.com/joescars/Functions.Bindings.DataLakeStore/blob/master/Functions.Bindings.DataLakeStore/DataLakeStoreStreamBuilder.cs#L13

**Comment by rozele** [comment]
Be consistent about sort-order of namespaces. I tend to prefer alphabetical-only, as that's what the Visual Studio defaults are. It makes it easier to reason about changes to the namespaces from open source contributions. If your namespaces aren't sorted consistently, some PR at a later point may sort them and make it more difficult to see what's changed.


E.g., https://github.com/joescars/Functions.Bindings.DataLakeStore/blob/master/Functions.Bindings.DataLakeStore/DataLakeStoreConfiguration.cs#L1-L2 is sorted alphabetically, https://github.com/joescars/Functions.Bindings.DataLakeStore/blob/master/Functions.Bindings.DataLakeStore/DataLakeStoreStreamBuilder.cs#L1-L6 is not sorted.

**Comment by rozele** [comment]
In `DataLakeStoreOutput`, your public property names start with a lowercase letter. According to the [.NET design guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members) "PascalCasing is always used for property names."

**Comment by rozele** [comment]
Lift https://github.com/joescars/Functions.Bindings.DataLakeStore/blob/master/Functions.Bindings.DataLakeStore/Services/DataLakeAdlsService.cs#L26 to a static field on the class.

**Comment by joescars** [comment]
all good points and they have been addressed. 

re: _adlsClient; left as async due to updating DataLakeAdlsService. As you noted, there are concurrency issues. 

re: synchronization context; removed and updated to use async/await. This code was based off of an old example and was never dove into. 

thanks again!
