### ISSUE TITLE
Improve async for DataLake IAsyncCollector

### ISSUE THREAD

**Issue by rozele** [joescars/Functions.Bindings.DataLakeStore#8]
If nothing else, you can use `adlsClient.CreateFileAsync` and `stream.CopyToAsync` in your `FlushAsync` implementation: 
https://github.com/joescars/Functions.Bindings.DataLakeStore/blob/29b1ba971cbaede276b9779fa4027fd25bb09f5e/Functions.Bindings.DataLakeStore/DataLakeStoreOutputAsyncCollector.cs#L42-L62

This will unblock any other activities the end user of the `IAsyncCollector` may be doing asynchronously on that thread.

I would also look into ways to more eagerly update the Data Lake from the `AddAsync` call, although I'll admit that I don't know the specific semantics for `IAsyncCollector`.

**Comment by joescars** [comment]
Updated per your suggestion. Also updated to update DataLake directly from `AddAsync`.
